export const matches = [
  { id: 1, group: 'A', date: '2026-06-11', homeTeam: 'Mexico', awayTeam: 'South Africa', homeCode: 'MX', awayCode: 'ZA', homeScore: 2, awayScore: 0 },
  { id: 2, group: 'A', date: '2026-06-11', homeTeam: 'South Korea', awayTeam: 'Czechia', homeCode: 'KR', awayCode: 'CZ', homeScore: 2, awayScore: 1 },
  { id: 3, group: 'B', date: '2026-06-12', homeTeam: 'Canada', awayTeam: 'Bosnia and Herzegovina', homeCode: 'CA', awayCode: 'BA', homeScore: 1, awayScore: 1 },
  { id: 4, group: 'D', date: '2026-06-12', homeTeam: 'United States', awayTeam: 'Paraguay', homeCode: 'US', awayCode: 'PY', homeScore: 4, awayScore: 1 },
  { id: 5, group: 'B', date: '2026-06-13', homeTeam: 'Qatar', awayTeam: 'Switzerland', homeCode: 'QA', awayCode: 'CH', homeScore: 1, awayScore: 1 },
  { id: 6, group: 'C', date: '2026-06-13', homeTeam: 'Brazil', awayTeam: 'Morocco', homeCode: 'BR', awayCode: 'MA', homeScore: 1, awayScore: 1 },
  { id: 7, group: 'C', date: '2026-06-13', homeTeam: 'Haiti', awayTeam: 'Scotland', homeCode: 'HT', awayCode: 'GB-SCT', homeScore: 0, awayScore: 1 },
  { id: 8, group: 'D', date: '2026-06-13', homeTeam: 'Australia', awayTeam: 'Türkiye', homeCode: 'AU', awayCode: 'TR', homeScore: 2, awayScore: 0 },
  { id: 9, group: 'E', date: '2026-06-14', homeTeam: 'Germany', awayTeam: 'Curaçao', homeCode: 'DE', awayCode: 'CW', homeScore: 7, awayScore: 1 },
  { id: 10, group: 'F', date: '2026-06-14', homeTeam: 'Netherlands', awayTeam: 'Japan', homeCode: 'NL', awayCode: 'JP', homeScore: 2, awayScore: 2 },
  { id: 11, group: 'E', date: '2026-06-14', homeTeam: "Côte d'Ivoire", awayTeam: 'Ecuador', homeCode: 'CI', awayCode: 'EC', homeScore: 1, awayScore: 0 },
  { id: 12, group: 'F', date: '2026-06-14', homeTeam: 'Sweden', awayTeam: 'Tunisia', homeCode: 'SE', awayCode: 'TN', homeScore: 5, awayScore: 1 },
  { id: 13, group: 'H', date: '2026-06-15', homeTeam: 'Spain', awayTeam: 'Cabo Verde', homeCode: 'ES', awayCode: 'CV', homeScore: 0, awayScore: 0 },
  { id: 14, group: 'G', date: '2026-06-15', homeTeam: 'Belgium', awayTeam: 'Egypt', homeCode: 'BE', awayCode: 'EG', homeScore: 1, awayScore: 1 },
  { id: 15, group: 'H', date: '2026-06-15', homeTeam: 'Saudi Arabia', awayTeam: 'Uruguay', homeCode: 'SA', awayCode: 'UY', homeScore: 1, awayScore: 1 },
  { id: 16, group: 'G', date: '2026-06-15', homeTeam: 'Iran', awayTeam: 'New Zealand', homeCode: 'IR', awayCode: 'NZ', homeScore: 2, awayScore: 2 },
  { id: 17, group: 'I', date: '2026-06-16', homeTeam: 'France', awayTeam: 'Senegal', homeCode: 'FR', awayCode: 'SN', homeScore: 3, awayScore: 1 },
  { id: 18, group: 'I', date: '2026-06-16', homeTeam: 'Iraq', awayTeam: 'Norway', homeCode: 'IQ', awayCode: 'NO', homeScore: 1, awayScore: 4 },
  { id: 19, group: 'J', date: '2026-06-16', homeTeam: 'Argentina', awayTeam: 'Algeria', homeCode: 'AR', awayCode: 'DZ', homeScore: 3, awayScore: 0 },
  { id: 20, group: 'J', date: '2026-06-16', homeTeam: 'Austria', awayTeam: 'Jordan', homeCode: 'AT', awayCode: 'JO', homeScore: 3, awayScore: 1 },
  { id: 21, group: 'K', date: '2026-06-17', homeTeam: 'Portugal', awayTeam: 'DR Congo', homeCode: 'PT', awayCode: 'CD', homeScore: 1, awayScore: 1 },
  { id: 22, group: 'L', date: '2026-06-17', homeTeam: 'England', awayTeam: 'Croatia', homeCode: 'GB-ENG', awayCode: 'HR', homeScore: 4, awayScore: 2 },
  { id: 23, group: 'L', date: '2026-06-17', homeTeam: 'Ghana', awayTeam: 'Panama', homeCode: 'GH', awayCode: 'PA', homeScore: 1, awayScore: 0 },
  { id: 24, group: 'K', date: '2026-06-17', homeTeam: 'Uzbekistan', awayTeam: 'Colombia', homeCode: 'UZ', awayCode: 'CO', homeScore: 1, awayScore: 3 },
  { id: 25, group: 'A', date: '2026-06-18', homeTeam: 'Czechia', awayTeam: 'South Africa', homeCode: 'CZ', awayCode: 'ZA', homeScore: 1, awayScore: 1 },
  { id: 26, group: 'B', date: '2026-06-18', homeTeam: 'Switzerland', awayTeam: 'Bosnia and Herzegovina', homeCode: 'CH', awayCode: 'BA', homeScore: 4, awayScore: 1 },
  { id: 27, group: 'B', date: '2026-06-18', homeTeam: 'Canada', awayTeam: 'Qatar', homeCode: 'CA', awayCode: 'QA', homeScore: 6, awayScore: 0 },
  { id: 28, group: 'A', date: '2026-06-18', homeTeam: 'Mexico', awayTeam: 'South Korea', homeCode: 'MX', awayCode: 'KR', homeScore: 1, awayScore: 0 },
  { id: 29, group: 'D', date: '2026-06-19', homeTeam: 'United States', awayTeam: 'Australia', homeCode: 'US', awayCode: 'AU', homeScore: 2, awayScore: 0 },
  { id: 30, group: 'C', date: '2026-06-19', homeTeam: 'Scotland', awayTeam: 'Morocco', homeCode: 'GB-SCT', awayCode: 'MA', homeScore: 0, awayScore: 1 },
  { id: 31, group: 'C', date: '2026-06-19', homeTeam: 'Brazil', awayTeam: 'Haiti', homeCode: 'BR', awayCode: 'HT', homeScore: 3, awayScore: 0 },
  { id: 32, group: 'D', date: '2026-06-19', homeTeam: 'Türkiye', awayTeam: 'Paraguay', homeCode: 'TR', awayCode: 'PY', homeScore: 0, awayScore: 1 },
  { id: 33, group: 'F', date: '2026-06-20', homeTeam: 'Netherlands', awayTeam: 'Sweden', homeCode: 'NL', awayCode: 'SE', homeScore: 5, awayScore: 1 },
  { id: 34, group: 'E', date: '2026-06-20', homeTeam: 'Germany', awayTeam: "Côte d'Ivoire", homeCode: 'DE', awayCode: 'CI', homeScore: 2, awayScore: 1 },
  { id: 35, group: 'E', date: '2026-06-20', homeTeam: 'Ecuador', awayTeam: 'Curaçao', homeCode: 'EC', awayCode: 'CW', homeScore: 0, awayScore: 0 },
  { id: 36, group: 'F', date: '2026-06-20', homeTeam: 'Tunisia', awayTeam: 'Japan', homeCode: 'TN', awayCode: 'JP', homeScore: 0, awayScore: 4 },
  { id: 37, group: 'H', date: '2026-06-21', homeTeam: 'Spain', awayTeam: 'Saudi Arabia', homeCode: 'ES', awayCode: 'SA', homeScore: 4, awayScore: 0 },
  { id: 38, group: 'G', date: '2026-06-21', homeTeam: 'Belgium', awayTeam: 'Iran', homeCode: 'BE', awayCode: 'IR', homeScore: 0, awayScore: 0 },
  { id: 39, group: 'H', date: '2026-06-21', homeTeam: 'Uruguay', awayTeam: 'Cabo Verde', homeCode: 'UY', awayCode: 'CV', homeScore: 2, awayScore: 2 },
  { id: 40, group: 'G', date: '2026-06-21', homeTeam: 'New Zealand', awayTeam: 'Egypt', homeCode: 'NZ', awayCode: 'EG', homeScore: 1, awayScore: 3 },
  { id: 41, group: 'J', date: '2026-06-22', homeTeam: 'Argentina', awayTeam: 'Austria', homeCode: 'AR', awayCode: 'AT', homeScore: 2, awayScore: 0 },
  { id: 42, group: 'I', date: '2026-06-22', homeTeam: 'France', awayTeam: 'Iraq', homeCode: 'FR', awayCode: 'IQ', homeScore: 3, awayScore: 0 },
  { id: 43, group: 'I', date: '2026-06-22', homeTeam: 'Norway', awayTeam: 'Senegal', homeCode: 'NO', awayCode: 'SN', homeScore: 3, awayScore: 2 },
  { id: 44, group: 'J', date: '2026-06-22', homeTeam: 'Jordan', awayTeam: 'Algeria', homeCode: 'JO', awayCode: 'DZ', homeScore: 1, awayScore: 2 },
  { id: 45, group: 'K', date: '2026-06-23', homeTeam: 'Portugal', awayTeam: 'Uzbekistan', homeCode: 'PT', awayCode: 'UZ', homeScore: 5, awayScore: 0 },
  { id: 46, group: 'L', date: '2026-06-23', homeTeam: 'England', awayTeam: 'Ghana', homeCode: 'GB-ENG', awayCode: 'GH', homeScore: 0, awayScore: 0 },
  { id: 47, group: 'L', date: '2026-06-23', homeTeam: 'Panama', awayTeam: 'Croatia', homeCode: 'PA', awayCode: 'HR', homeScore: 0, awayScore: 1 },
  { id: 48, group: 'K', date: '2026-06-23', homeTeam: 'Colombia', awayTeam: 'DR Congo', homeCode: 'CO', awayCode: 'CD', homeScore: 1, awayScore: 0 },
  { id: 49, group: 'B', date: '2026-06-24', homeTeam: 'Switzerland', awayTeam: 'Canada', homeCode: 'CH', awayCode: 'CA', homeScore: 2, awayScore: 1 },
  { id: 50, group: 'B', date: '2026-06-24', homeTeam: 'Bosnia and Herzegovina', awayTeam: 'Qatar', homeCode: 'BA', awayCode: 'QA', homeScore: 3, awayScore: 1 },
  { id: 51, group: 'C', date: '2026-06-24', homeTeam: 'Morocco', awayTeam: 'Haiti', homeCode: 'MA', awayCode: 'HT', homeScore: 4, awayScore: 2 },
  { id: 52, group: 'C', date: '2026-06-24', homeTeam: 'Scotland', awayTeam: 'Brazil', homeCode: 'GB-SCT', awayCode: 'BR', homeScore: 0, awayScore: 3 },
  { id: 53, group: 'A', date: '2026-06-24', homeTeam: 'South Africa', awayTeam: 'South Korea', homeCode: 'ZA', awayCode: 'KR', homeScore: 1, awayScore: 0 },
  { id: 54, group: 'A', date: '2026-06-24', homeTeam: 'Czechia', awayTeam: 'Mexico', homeCode: 'CZ', awayCode: 'MX', homeScore: 0, awayScore: 3 },
  { id: 55, group: 'E', date: '2026-06-25', homeTeam: 'Curaçao', awayTeam: "Côte d'Ivoire", homeCode: 'CW', awayCode: 'CI', homeScore: 0, awayScore: 2 },
  { id: 56, group: 'E', date: '2026-06-25', homeTeam: 'Ecuador', awayTeam: 'Germany', homeCode: 'EC', awayCode: 'DE', homeScore: 2, awayScore: 1 },
  { id: 57, group: 'F', date: '2026-06-25', homeTeam: 'Tunisia', awayTeam: 'Netherlands', homeCode: 'TN', awayCode: 'NL', homeScore: 1, awayScore: 3 },
  { id: 58, group: 'F', date: '2026-06-25', homeTeam: 'Japan', awayTeam: 'Sweden', homeCode: 'JP', awayCode: 'SE', homeScore: 1, awayScore: 1 },
  { id: 59, group: 'D', date: '2026-06-25', homeTeam: 'Türkiye', awayTeam: 'United States', homeCode: 'TR', awayCode: 'US', homeScore: 3, awayScore: 2 },
  { id: 60, group: 'D', date: '2026-06-25', homeTeam: 'Paraguay', awayTeam: 'Australia', homeCode: 'PY', awayCode: 'AU', homeScore: 0, awayScore: 0 },
  { id: 61, group: 'I', date: '2026-06-26', homeTeam: 'Norway', awayTeam: 'France', homeCode: 'NO', awayCode: 'FR', homeScore: 1, awayScore: 4 },
  { id: 62, group: 'I', date: '2026-06-26', homeTeam: 'Senegal', awayTeam: 'Iraq', homeCode: 'SN', awayCode: 'IQ', homeScore: 5, awayScore: 0 },
  { id: 63, group: 'H', date: '2026-06-26', homeTeam: 'Cabo Verde', awayTeam: 'Saudi Arabia', homeCode: 'CV', awayCode: 'SA', homeScore: 0, awayScore: 0 },
  { id: 64, group: 'H', date: '2026-06-26', homeTeam: 'Uruguay', awayTeam: 'Spain', homeCode: 'UY', awayCode: 'ES', homeScore: 0, awayScore: 1 },
  { id: 65, group: 'G', date: '2026-06-26', homeTeam: 'New Zealand', awayTeam: 'Belgium', homeCode: 'NZ', awayCode: 'BE', homeScore: 1, awayScore: 5 },
  { id: 66, group: 'G', date: '2026-06-26', homeTeam: 'Egypt', awayTeam: 'Iran', homeCode: 'EG', awayCode: 'IR', homeScore: 1, awayScore: 1 },
]
